// 中医智能诊疗 - 中草药完整数据库
// 涵盖解表药、清热药、泻下药、祛湿药、温里药、理气药、活血药、止血药、化痰药、补虚药、收涩药等
const TCM_HERB_DB = [
  // ========== 解表药 ==========
  {
    id:'mahuang', name:'麻黄', alias:'龙沙、草麻黄', category:'jiebiao',
    prop:'辛、微苦，温', meridian:'肺、膀胱',
    effect:'发汗解表，宣肺平喘，利水消肿',
    indication:'风寒感冒、胸闷喘咳、风水浮肿、支气管哮喘',
    dosage:'2-10g，发汗解表宜生用，平喘止咳宜炙用',
    origin:'内蒙古、山西、河北、甘肃、新疆',
    bestOrigin:'内蒙古赤峰、山西大同（道地药材）',
    harvest:'秋季采割绿色草质茎，晒干',
    processing:'生麻黄（切段）、蜜麻黄（蜜炙）、麻黄绒',
    contraindication:'体虚多汗、肺虚咳喘、高血压者慎用',
    wildFeature:'野生茎更细瘦，节间短，颜色深绿偏黄，质地坚韧，断面纤维性强',
    plantedFeature:'种植茎较粗壮均匀，节间较长，颜色鲜绿，质地稍软',
    identifyTips:'野生品香气浓烈、味苦涩明显；种植品香气较淡、苦味轻。野生根部木质化程度高',
    appearance:'草质茎细长圆柱形，少分枝，直径1-2mm，表面浅绿至黄绿色，有细纵棱，节上有膜质鳞叶，对生',
    notes:'麻黄碱有兴奋中枢神经作用，运动员禁用'
  },
  {
    id:'guizhi', name:'桂枝', alias:'柳桂', category:'jiebiao',
    prop:'辛、甘，温', meridian:'心、肺、膀胱',
    effect:'发汗解肌，温通经脉，助阳化气',
    indication:'风寒感冒、寒凝血滞、痰饮蓄水、心悸',
    dosage:'3-10g',
    origin:'广西、广东、云南',
    bestOrigin:'广西平南、岑溪（肉桂道地产区嫩枝）',
    harvest:'春、夏二季采收嫩枝，晒干或阴干',
    processing:'切薄片或段用',
    contraindication:'温热病及阴虚火旺者忌用，孕妇慎用',
    wildFeature:'野生桂枝较细、皮薄、油性足、香气浓郁持久',
    plantedFeature:'种植桂枝较粗壮、皮稍厚、香气稍淡',
    identifyTips:'正品桂枝外皮红棕色，断面可见明显油点，嚼之辛辣甜味明显，香气持久',
    appearance:'长圆柱形，多分枝，长30-75cm，粗端径0.3-1cm，表面红棕色至暗棕色，有纵棱线及小疙瘩状叶痕',
    notes:'与肉桂同源，桂枝为嫩枝，肉桂为树皮'
  },
  {
    id:'zisuye', name:'紫苏叶', alias:'苏叶、赤苏', category:'jiebiao',
    prop:'辛，温', meridian:'肺、脾',
    effect:'解表散寒，行气和胃，解鱼蟹毒',
    indication:'风寒感冒、咳嗽呕恶、妊娠呕吐、鱼蟹中毒',
    dosage:'5-10g，不宜久煎',
    origin:'全国各地均有栽培',
    bestOrigin:'广东、广西（广紫苏）、湖北（湖紫苏）',
    harvest:'夏季枝叶茂盛时采收，摊晒或阴干',
    processing:'生用或姜汁炒',
    contraindication:'气虚表虚者慎用',
    wildFeature:'野生紫苏叶片较小，颜色深紫，香气浓烈，叶面皱缩明显',
    plantedFeature:'种植紫苏叶片大而平展，颜色可能偏绿紫，香气稍淡',
    identifyTips:'正品两面均为紫色或上绿下紫，揉碎有强烈芳香。伪品叶形相似但无特殊香气',
    appearance:'叶片多皱缩卷曲，完整者呈卵圆形，边缘有锯齿，两面紫色或上绿下紫，疏生灰白色毛',
    notes:'紫苏叶、紫苏梗、紫苏子功效各异，需分别使用'
  },
  {
    id:'jingjie', name:'荆芥', alias:'假苏、四棱杆蒿', category:'jiebiao',
    prop:'辛，微温', meridian:'肺、肝',
    effect:'祛风解表，透疹消疮，止血',
    indication:'感冒头痛、麻疹不透、疮疡初起、吐衄下血',
    dosage:'5-10g，止血宜炒炭用',
    origin:'江苏、浙江、河北、江西',
    bestOrigin:'江苏太仓（道地药材）',
    harvest:'秋季花开穗绿时割取地上部分',
    processing:'切段生用或炒炭',
    contraindication:'表虚自汗、阴虚头痛者忌用',
    wildFeature:'野生荆芥茎较细瘦，分枝多，穗短密，香气浓',
    plantedFeature:'种植荆芥茎粗壮，穗较长松散，香气较淡',
    identifyTips:'正品揉之有强烈芳香，茎方形中空。荆芥穗比荆芥茎药力强',
    appearance:'茎方形，上部多分枝，表面淡紫红色，被短柔毛。叶对生3-5深裂，穗状花序顶生',
    notes:'荆芥穗祛风力强，荆芥炭止血力强'
  },
  {
    id:'fangfeng', name:'防风', alias:'铜芸、百蜚', category:'jiebiao',
    prop:'辛、甘，微温', meridian:'膀胱、肝、脾',
    effect:'祛风解表，胜湿止痛，止痉',
    indication:'感冒头痛、风湿痹痛、风疹瘙痒、破伤风',
    dosage:'5-10g',
    origin:'黑龙江、内蒙古、吉林、辽宁',
    bestOrigin:'黑龙江齐齐哈尔（关防风，道地药材）',
    harvest:'春秋二季采挖根部，晒干',
    processing:'切片生用或炒炭',
    contraindication:'阴虚火旺、血虚发痉者慎用',
    wildFeature:'野生防风根头部有明显"蚯蚓头"（密集横环纹），根条长而均匀，皮部棕褐色紧实',
    plantedFeature:'种植品根头环纹少或无，根较粗短，分叉多，皮色较浅',
    identifyTips:'野生品根头残存棕褐色纤维状叶基（"蚯蚓头"）是最重要鉴别点。断面有裂隙，皮部浅棕色，有放射状纹理',
    appearance:'根呈长圆锥形或长圆柱形，根头部有明显密集环纹及棕褐色毛状残存叶基',
    notes:'防风为"风药之润剂"，祛风而不燥'
  },
  {
    id:'bohe', name:'薄荷', alias:'银丹草、仁丹草', category:'jiebiao',
    prop:'辛，凉', meridian:'肺、肝',
    effect:'疏散风热，清利头目，利咽透疹，疏肝行气',
    indication:'风热感冒、温病初起、头痛目赤、咽喉肿痛、麻疹不透、肝郁气滞',
    dosage:'3-6g，后下',
    origin:'江苏、浙江、江西',
    bestOrigin:'江苏太仓（苏薄荷，道地药材）',
    harvest:'夏秋二季茎叶茂盛或花开时采割',
    processing:'阴干切段',
    contraindication:'阴虚血燥、肝阳偏亢、表虚多汗者忌用',
    wildFeature:'野生薄荷茎细瘦，叶小而厚，气味特别浓烈清凉',
    plantedFeature:'种植薄荷茎较粗，叶大而薄，香气清凉但略淡',
    identifyTips:'揉碎后有特殊清凉芳香是最重要鉴别特征。茎方形有毛，叶对生有锯齿',
    appearance:'茎方柱形，有对生分枝，表面紫棕色或淡绿色，具毛。叶对生，叶片薄，多皱缩',
    notes:'薄荷入汤剂宜后下，以免挥发油散失'
  },
  {
    id:'chaihu', name:'柴胡', alias:'地熏、茹草', category:'jiebiao',
    prop:'辛、苦，微寒', meridian:'肝、胆、肺',
    effect:'和解表里，疏肝升阳',
    indication:'寒热往来、胸胁胀痛、月经不调、子宫脱垂、脱肛',
    dosage:'3-10g，疏肝解郁宜醋炙',
    origin:'河北、河南、湖北、四川',
    bestOrigin:'河北承德（北柴胡，道地药材）',
    harvest:'春秋二季采挖根部',
    processing:'切片生用或醋炙',
    contraindication:'肝阳上亢、阴虚火旺者慎用',
    wildFeature:'野生北柴胡根细长单一，少分叉，质硬而韧，表面黑褐色，具纵皱纹，断面纤维性',
    plantedFeature:'种植品根粗短，分叉多，表面浅棕色，质较松',
    identifyTips:'北柴胡质硬断面显纤维性；南柴胡质较软，有败油气。伪品前胡根较粗，有油点',
    appearance:'根呈圆锥形，主根顺直或稍弯曲，表面黑褐色或浅棕色，具纵皱纹、支根痕及皮孔',
    notes:'北柴胡与南柴胡功效有异，处方中柴胡通常指北柴胡'
  },
  {
    id:'gegen', name:'葛根', alias:'干葛、甘葛', category:'jiebiao',
    prop:'甘、辛，凉', meridian:'脾、胃、肺',
    effect:'解肌退热，透疹，生津止渴，升阳止泻',
    indication:'外感发热、麻疹不透、热病口渴、消渴、泄泻',
    dosage:'10-15g',
    origin:'湖南、河南、广东、浙江、四川',
    bestOrigin:'湖南湘西、广西（粉葛道地产区）',
    harvest:'秋冬二季采挖',
    processing:'切片晒干，或趁鲜切片',
    contraindication:'胃寒呕吐及表虚多汗者不宜',
    wildFeature:'野生葛根纤维多，粉性足，质坚实沉重，断面纤维性强，有浓郁豆腥气',
    plantedFeature:'种植葛根肉质较肥大，纤维较少，粉性稍逊，质较轻',
    identifyTips:'正品有浓郁豆腥味，断面可见明显纤维及淀粉颗粒。粉葛肉质肥厚，野葛纤维性强',
    appearance:'纵切或斜切厚片，切面黄白色，纹理不明显，纤维性强，质韧',
    notes:'葛根素有扩张冠状动脉、降血压作用'
  },
  // ========== 清热药 ==========
  {
    id:'huangqin', name:'黄芩', alias:'枯芩、条芩', category:'qingre',
    prop:'苦，寒', meridian:'肺、胆、脾、大肠、小肠',
    effect:'清热燥湿，泻火解毒，止血，安胎',
    indication:'湿温暑湿、肺热咳嗽、高热烦渴、湿热泻痢、黄疸、胎动不安',
    dosage:'3-10g',
    origin:'河北、山西、内蒙古、甘肃',
    bestOrigin:'河北承德（热河黄芩，道地药材）',
    harvest:'春秋二季采挖',
    processing:'切片生用、酒炙或炒炭',
    contraindication:'脾胃虚寒者不宜',
    wildFeature:'野生黄芩根条细长，外皮暗棕色粗糙，质坚实，断面深黄色，老根中心多枯朽（枯芩）',
    plantedFeature:'种植品根较粗短，外皮浅黄棕色较光滑，少枯心',
    identifyTips:'枯芩（老根中空）善清肺火；条芩（幼根实心）善清大肠湿热。断面鲜黄色为佳，发绿变质',
    appearance:'根呈圆锥形，扭曲，表面棕黄色或深黄色，有不规则纵皱纹，质硬脆，断面黄色',
    notes:'黄芩苷有广谱抗菌作用，现代用于抗感染'
  },
  {
    id:'huanglian', name:'黄连', alias:'川连、鸡爪连', category:'qingre',
    prop:'苦，寒', meridian:'心、脾、胃、肝、胆、大肠',
    effect:'清热燥湿，泻火解毒',
    indication:'湿热泻痢、高热神昏、心火亢盛、目赤口疮、胃热呕吐',
    dosage:'2-5g',
    origin:'四川、湖北、贵州、云南',
    bestOrigin:'四川石柱、利川（川黄连/味连，道地药材）',
    harvest:'秋季采挖，除去须根及泥沙',
    processing:'切片生用、姜汁炒或酒炒',
    contraindication:'脾胃虚寒者忌用，苦燥伤阴',
    wildFeature:'野生黄连根茎形如鸡爪，分枝短密，表面灰褐色粗糙，质坚硬',
    plantedFeature:'种植品根茎稍粗长，分枝较少较整齐，表面较光洁',
    identifyTips:'正品断面鲜黄色，味极苦。以"鸡爪形"、质坚实、断面红黄色者为佳。伪品岩黄连味淡',
    appearance:'根茎多簇状分枝，弯曲形如鸡爪，表面灰黄色或黄褐色，有不规则结节状突起',
    notes:'黄连为"清热燥湿第一药"，小檗碱含量高'
  },
  {
    id:'huangbai', name:'黄柏', alias:'黄檗、川柏', category:'qingre',
    prop:'苦，寒', meridian:'肾、膀胱、大肠',
    effect:'清热燥湿，泻火除蒸，解毒疗疮',
    indication:'湿热带下、热淋、骨蒸潮热、盗汗遗精、疮疡肿毒',
    dosage:'3-12g',
    origin:'四川、贵州、辽宁、吉林',
    bestOrigin:'四川（川黄柏）、辽宁（关黄柏）',
    harvest:'剥取树皮，晒干',
    processing:'切丝生用或盐水炒',
    contraindication:'脾胃虚寒者忌用',
    wildFeature:'野生黄柏树皮厚而致密，外皮灰棕色粗糙有厚栓皮层，内面深黄色',
    plantedFeature:'种植品树皮较薄，栓皮层薄，内面黄色稍浅',
    identifyTips:'内面深黄色、嚼之极苦且染唾液为黄色是正品特征。川黄柏皮较厚，关黄柏皮较薄',
    appearance:'板片状或浅槽状，外面黄棕色或黄褐色，内面暗黄色或淡棕色，划之显鲜黄色',
    notes:'与知母相须为用（滋阴降火经典配伍）'
  },
  {
    id:'jinyinhua', name:'金银花', alias:'忍冬花、双花', category:'qingre',
    prop:'甘，寒', meridian:'肺、心、胃',
    effect:'清热解毒，疏散风热',
    indication:'温病发热、热毒血痢、痈肿疔疮、咽喉肿痛、外感风热',
    dosage:'6-15g',
    origin:'山东、河南、河北',
    bestOrigin:'山东平邑（密银花，道地药材）、河南封丘',
    harvest:'夏初花开放前采收花蕾',
    processing:'阴干或低温烘干',
    contraindication:'脾胃虚寒及疮疡属阴证者忌用',
    wildFeature:'野生金银花花蕾小而紧密，颜色黄白分明，香气浓郁，含苞待放时最佳',
    plantedFeature:'种植品花蕾较大较匀，产量高但有效成分可能稍低',
    identifyTips:'以花蕾未开放、色黄白、肥大者为佳。开放之花药力下降。注意区分山银花（华南忍冬）',
    appearance:'花蕾呈棒状，上粗下细，表面黄白色或绿白色，密被短柔毛',
    notes:'金银花与山银花（2005年药典分列）功效相近但品种不同'
  },
  {
    id:'lianqiao', name:'连翘', alias:'旱连子、大翘子', category:'qingre',
    prop:'苦，微寒', meridian:'肺、心、小肠',
    effect:'清热解毒，消肿散结，疏散风热',
    indication:'温病初起、风热感冒、热入营血、痈肿疮毒、瘰疬瘿瘤',
    dosage:'6-15g',
    origin:'山西、陕西、河南、山东',
    bestOrigin:'山西（道地药材）',
    harvest:'秋季果实初熟或成熟时采收',
    processing:'蒸后晒干（青翘/老翘）',
    contraindication:'脾胃虚弱、气虚发热者不宜',
    wildFeature:'野生连翘果实较小，壳厚质坚，种子饱满，表面色深有疣点',
    plantedFeature:'种植品果实较大均匀，壳较薄',
    identifyTips:'青翘（未熟果）清热力强；老翘（成熟果）散结力佳。正品不开裂为青翘，已裂为老翘',
    appearance:'果实呈长卵形至卵形，表面有不规则纵皱纹及凸起小斑点，中央有纵沟',
    notes:'连翘有"疮家圣药"之称'
  },
  {
    id:'zhizi', name:'栀子', alias:'山栀、黄栀子', category:'qingre',
    prop:'苦，寒', meridian:'心、肺、三焦',
    effect:'泻火除烦，清热利湿，凉血解毒',
    indication:'热病心烦、黄疸尿赤、血淋涩痛、目赤肿痛、火毒疮疡',
    dosage:'6-10g',
    origin:'江西、湖南、浙江、福建',
    bestOrigin:'江西樟树、抚州（道地药材）',
    harvest:'9-11月果实成熟呈红黄色时采收',
    processing:'生用、炒焦或炒炭',
    contraindication:'脾虚便溏者不宜',
    wildFeature:'野生栀子果实小而圆，皮薄，颜色深红，香气浓',
    plantedFeature:'种植品果实较大，多为长卵形，颜色橙黄',
    identifyTips:'正品外表红黄色或棕红色，有6-8条翅状纵棱。以皮薄、饱满、色红黄者为佳',
    appearance:'果实长卵形或椭圆形，表面红黄色或棕红色，有翅状纵棱5-8条，顶端有宿萼',
    notes:'栀子苷有降压保肝作用'
  },
  // ========== 泻下药 ==========
  {
    id:'dahuang', name:'大黄', alias:'将军、川军', category:'xiaxia',
    prop:'苦，寒', meridian:'脾、胃、大肠、肝、心包',
    effect:'泻下攻积，清热泻火，凉血解毒，逐瘀通经',
    indication:'实热便秘、积滞腹痛、湿热黄疸、血热吐衄、瘀血经闭、痈肿疔疮',
    dosage:'3-15g，泻下宜后下',
    origin:'青海、甘肃、四川、云南、西藏',
    bestOrigin:'青海（西宁大黄）、甘肃礼县（铨水大黄，道地药材）',
    harvest:'秋末冬初或次春采挖',
    processing:'切片生用、酒炒或炒炭',
    contraindication:'脾胃虚弱、孕妇、经期、哺乳期忌用',
    wildFeature:'野生大黄根茎粗大坚实，断面有明显放射状纹理（星点），色深黄棕，气特异',
    plantedFeature:'种植品形体较规则，星点可能较稀疏，气味稍淡',
    identifyTips:'断面可见星点（异常维管束）是正品鉴别关键。嚼之粘牙、有沙感。染唾液为黄色',
    appearance:'类圆柱形、圆锥形或块片状，表面黄棕色至红棕色，可见类白色网状纹理',
    notes:'大黄泻下力强，用量宜从小量开始，后下泻下力强，久煎泻下力弱'
  },
  {
    id:'mangxiao', name:'芒硝', alias:'朴硝、皮硝', category:'xiaxia',
    prop:'咸、苦，寒', meridian:'胃、大肠',
    effect:'泻下通便，润燥软坚，清火消肿',
    indication:'实热积滞、大便燥结、肠痈腹痛、目赤肿痛、口疮',
    dosage:'6-12g，冲入药汁内或开水溶化后服',
    origin:'河北、河南、山东、江苏、安徽',
    bestOrigin:'四川（川硝）',
    harvest:'多于秋季加工自然界芒硝矿',
    processing:'芒硝（含结晶水）、玄明粉（风化失水）',
    contraindication:'孕妇及哺乳期忌用，脾胃虚寒者忌',
    wildFeature:'天然矿物，无野生种植之分',
    plantedFeature:'通过矿物加工精制',
    identifyTips:'正品为无色透明棱柱状结晶，味咸苦而微涩凉。玄明粉为白色粉末',
    appearance:'棱柱状或长方形结晶，无色透明，暴露空气中易风化变为白色粉末',
    notes:'大黄配芒硝为"大承气汤"核心配伍'
  },
  // ========== 祛湿药 ==========
  {
    id:'fuling', name:'茯苓', alias:'云苓、白茯苓', category:'qushi',
    prop:'甘、淡，平', meridian:'心、肺、脾、肾',
    effect:'利水渗湿，健脾宁心',
    indication:'水肿尿少、痰饮眩悸、脾虚食少、心神不安、失眠',
    dosage:'10-15g',
    origin:'云南、安徽、湖北、河南',
    bestOrigin:'云南（云苓，道地药材）、安徽岳西',
    harvest:'多于7-9月采挖',
    processing:'鲜茯苓削去外皮，切块或片，干燥',
    contraindication:'虚寒精滑者慎用',
    wildFeature:'野生茯苓（松树根附近）个体小而不规则，外皮黑褐色粗糙，质坚实而重',
    plantedFeature:'种植品（接种松木段）个体大而规则，外皮棕褐色稍光滑',
    identifyTips:'正品外皮黑褐色粗糙，切面白色或淡粉红色。嚼之粘牙。茯神（抱松根者）安神力强',
    appearance:'不规则球形、扁球形或块状，大小不一，外皮薄而粗糙，棕褐色至黑褐色',
    notes:'茯苓为"四时神药"，性平和不伤正'
  },
  {
    id:'yiyiren', name:'薏苡仁', alias:'薏米、苡仁', category:'qushi',
    prop:'甘、淡，凉', meridian:'脾、胃、肺',
    effect:'利水渗湿，健脾止泻，除痹，排脓',
    indication:'水肿、脚气、小便不利、脾虚泄泻、湿痹拘挛、肺痈、肠痈',
    dosage:'10-30g',
    origin:'福建、河北、辽宁、贵州',
    bestOrigin:'福建浦城（道地药材）、贵州兴仁',
    harvest:'秋季果实成熟时采收',
    processing:'生用或麸炒',
    contraindication:'孕妇慎用（有兴奋子宫作用）',
    wildFeature:'野生薏苡仁粒小而饱满，质坚硬，外壳黑灰色厚实',
    plantedFeature:'种植品粒大而白，外壳薄，去壳后仁白色肥大',
    identifyTips:'正品仁白色或淡黄色，质坚硬，断面粉性。伪品薏苡壳较薄，仁多空瘪',
    appearance:'卵圆形或椭圆形，背面圆凸，腹面有宽沟，表面乳白色，光滑',
    notes:'生薏仁利湿排脓，炒薏仁健脾止泻'
  },
  {
    id:'cheqianzi', name:'车前子', alias:'车轮菜子', category:'qushi',
    prop:'甘，微寒', meridian:'肝、肾、肺、小肠',
    effect:'清热利尿，渗湿止泻，明目，祛痰',
    indication:'热淋涩痛、水肿胀满、暑湿泄泻、痰热咳嗽、目赤肿痛',
    dosage:'10-15g，宜包煎',
    origin:'全国各地',
    bestOrigin:'江西（道地药材）、河南',
    harvest:'夏秋二季种子成熟时采收',
    processing:'生用或盐水炒',
    contraindication:'肾虚精滑者慎用',
    wildFeature:'野生车前子粒小而饱满，色黑褐，遇水膨胀粘性强',
    plantedFeature:'种植品粒稍大均匀，色浅褐',
    identifyTips:'正品加水浸泡后外皮有明显粘液膨胀。色黑褐或棕褐色，一面有灰白色凹点',
    appearance:'椭圆形或不规则长圆形，略扁，表面黄棕色至黑褐色，有细皱纹',
    notes:'车前子利水而不伤阴，常与利水药同用'
  },
  // ========== 温里药 ==========
  {
    id:'fuzi', name:'附子', alias:'黑顺片、白附片', category:'wenli',
    prop:'辛、甘，大热，有毒', meridian:'心、肾、脾',
    effect:'回阳救逆，补火助阳，散寒止痛',
    indication:'亡阳证（四肢厥逆、脉微欲绝）、阳虚证、寒湿痹痛',
    dosage:'3-15g，先煎30-60分钟',
    origin:'四川、陕西、云南',
    bestOrigin:'四川江油（道地药材，"江油附子"最为著名）',
    harvest:'夏至至小暑间采挖',
    processing:'盐附子、黑顺片、白附片等多种炮制品',
    contraindication:'阴虚阳亢者忌用，孕妇忌用。反半夏、瓜蒌、贝母、白蔹、白及',
    wildFeature:'野生乌头块根小而坚硬，毒性更大',
    plantedFeature:'种植品（子根即附子）较大而饱满，经炮制后毒性降低',
    identifyTips:'正品煎煮后尝之应不麻口（充分炮制）。若感舌尖发麻说明炮制不够，需久煎。黑顺片切面角质样',
    appearance:'黑顺片为纵切片，上宽下窄，表面黑褐色有光泽，半透明状',
    notes:'附子为"回阳救逆第一品药"，必须充分炮制和久煎去毒'
  },
  {
    id:'ganjiang', name:'干姜', alias:'白姜、均姜', category:'wenli',
    prop:'辛，热', meridian:'脾、胃、肾、心、肺',
    effect:'温中散寒，回阳通脉，温肺化饮',
    indication:'脘腹冷痛、呕吐泄泻、亡阳证、寒饮咳喘',
    dosage:'3-10g',
    origin:'四川、贵州、广西、湖北',
    bestOrigin:'四川犍为（道地药材）',
    harvest:'冬季采挖',
    processing:'切片生用或炮制（炮姜/姜炭）',
    contraindication:'阴虚内热、血热妄行者忌用',
    wildFeature:'无明显野生品，均为栽培',
    plantedFeature:'姜块肥大，断面黄白色，粉性，气香味辣',
    identifyTips:'正品表面灰黄色或浅灰棕色，断面淡黄色，有明显油点和纤维。气香特异，味辛辣',
    appearance:'扁平块状，具指状分枝，表面灰黄色或浅灰棕色，质坚实，断面黄白色',
    notes:'生姜发表散寒，干姜温中回阳，炮姜温经止血'
  },
  {
    id:'rougui', name:'肉桂', alias:'玉桂、牡桂', category:'wenli',
    prop:'辛、甘，大热', meridian:'肾、脾、心、肝',
    effect:'补火助阳，引火归元，散寒止痛，温通经脉',
    indication:'阳痿宫冷、腰膝冷痛、虚阳上浮、心腹冷痛、经闭痛经',
    dosage:'1-5g，研末冲服或后下',
    origin:'广西、广东、云南',
    bestOrigin:'广西防城（桂皮产地，道地药材）',
    harvest:'多于秋季剥取树皮',
    processing:'刮去栓皮或不去栓皮',
    contraindication:'阴虚火旺、血热出血者忌用，孕妇忌',
    wildFeature:'野生肉桂树皮薄，油性足，香气极浓，含油量高',
    plantedFeature:'种植品（企边桂）树皮较厚规整，内面光滑红棕色',
    identifyTips:'正品嚼之先辣后甜，有粘滑感。以皮细肉厚、油性大、味甜辣、嚼后渣少者为佳',
    appearance:'槽状或卷筒状，外表面灰棕色稍粗糙，内表面红棕色而油润，划之有油痕',
    notes:'肉桂入汤剂宜后下或研末冲服，以免挥发油损失'
  },
  // ========== 理气药 ==========
  {
    id:'chenpi', name:'陈皮', alias:'橘皮、红皮', category:'liq',
    prop:'辛、苦，温', meridian:'脾、肺',
    effect:'理气健脾，燥湿化痰',
    indication:'脘腹胀满、食少吐泻、咳嗽痰多',
    dosage:'3-10g',
    origin:'广东、福建、四川、浙江',
    bestOrigin:'广东新会（新会陈皮，道地药材，越陈越好）',
    harvest:'秋末冬初果实成熟时采收果皮',
    processing:'晒干陈放，陈久者良',
    contraindication:'气虚、阴虚燥咳者慎用',
    wildFeature:'野生橘皮薄而小，油点密集，香气浓烈',
    plantedFeature:'栽培品（新会柑皮）皮厚油点大，陈放后油室更明显，气味醇和',
    identifyTips:'以陈久、外皮深褐内面黄白、油点大而凹入、气香味苦辛者为佳。新会陈皮三瓣相连为正品',
    appearance:'常3瓣相连，片状或不规则块，外表面橙红色或红棕色，有细皱纹及凹下油室',
    notes:'陈皮以陈久者良，存放时间越长药效越好'
  },
  {
    id:'xiangfu', name:'香附', alias:'莎草根、雷公头', category:'liq',
    prop:'辛、微苦、微甘，平', meridian:'肝、脾、三焦',
    effect:'疏肝解郁，理气宽中，调经止痛',
    indication:'肝郁气滞、胸胁胀痛、疝气腹痛、月经不调、经闭痛经',
    dosage:'6-10g',
    origin:'全国各地均有',
    bestOrigin:'广东海南（道地药材）',
    harvest:'秋季采挖根茎',
    processing:'生用、醋炙或酒炒',
    contraindication:'气虚无滞者不宜',
    wildFeature:'野生香附根茎细长，纺锤形明显，表面褐色，质坚硬',
    plantedFeature:'少有大规模种植，多为野生采集',
    identifyTips:'正品呈纺锤形，表面棕褐色，有纵皱纹及环节。气香，味微苦',
    appearance:'纺锤形，表面棕褐色或黑褐色，有纵皱纹，有的有环节，质坚硬',
    notes:'香附为"气病之总司，女科之主帅"'
  },
  // ========== 活血药 ==========
  {
    id:'danshen', name:'丹参', alias:'赤参、紫丹参', category:'huoxue',
    prop:'苦，微寒', meridian:'心、肝',
    effect:'活血祛瘀，通经止痛，清心除烦，凉血消痈',
    indication:'月经不调、心腹疼痛、癥瘕积聚、心烦失眠、痈肿疮毒',
    dosage:'10-15g',
    origin:'河北、安徽、江苏、四川',
    bestOrigin:'四川中江（川丹参，道地药材）',
    harvest:'春秋二季采挖根部',
    processing:'切片生用或酒炒',
    contraindication:'无瘀血者慎用，孕妇忌用，不宜与藜芦同用',
    wildFeature:'野生丹参根条细长，外皮暗红棕色，质坚实，断面角质样',
    plantedFeature:'种植品根较粗壮，外皮色浅红棕，质稍松',
    identifyTips:'正品外皮砖红色或暗棕红色，断面角质样有白色放射状纹理。与紫草根区分：丹参味淡微苦',
    appearance:'根茎短粗，根数条，长圆柱形，表面棕红色或暗棕红色，粗糙有纵皱纹',
    notes:'"一味丹参，功同四物"，为活血化瘀要药'
  },
  {
    id:'chuanxiong', name:'川芎', alias:'芎藭、大川芎', category:'huoxue',
    prop:'辛，温', meridian:'肝、胆、心包',
    effect:'活血行气，祛风止痛',
    indication:'月经不调、痛经、经闭、胸胁刺痛、头痛、风湿痹痛',
    dosage:'3-10g',
    origin:'四川、云南、贵州、湖北',
    bestOrigin:'四川都江堰灌县（道地药材）',
    harvest:'夏季茎节膨大、略带紫色时采挖',
    processing:'晒干切片',
    contraindication:'阴虚火旺、月经过多者慎用，孕妇慎用',
    wildFeature:'野生川芎少见，多为栽培',
    plantedFeature:'正品为不规则结节状拳形团块，质坚实，断面黄白色有油点',
    identifyTips:'正品断面有波状环纹（形成层）及散在油点，气浓香特异。蝴蝶结形的断面花纹是鉴别要点',
    appearance:'不规则结节状拳形团块，表面黄褐色粗糙有皱缩纹理，质坚实不易折断',
    notes:'川芎为"血中之气药"，上行头目，下行血海'
  },
  {
    id:'taoren', name:'桃仁', alias:'桃核仁', category:'huoxue',
    prop:'苦、甘，平', meridian:'心、肝、大肠',
    effect:'活血祛瘀，润肠通便，止咳平喘',
    indication:'经闭痛经、癥瘕痞块、跌打损伤、肠燥便秘',
    dosage:'5-10g，打碎入煎',
    origin:'全国各地',
    bestOrigin:'山东、河北、陕西',
    harvest:'果实成熟后收集果核，取出种仁',
    processing:'去皮生用或炒用',
    contraindication:'孕妇忌用，血虚无瘀者不宜',
    wildFeature:'野生品仁小而饱满，油性足',
    plantedFeature:'栽培品仁较大而扁平',
    identifyTips:'正品仁扁平长卵形，表面红棕色有颗粒状突起，味微苦。去皮后呈乳白色',
    appearance:'扁平长卵形，表面浅红棕色至棕色，有颗粒状突起和短沟纹',
    notes:'桃仁性善破血，妊娠期禁用'
  },
  // ========== 止血药 ==========
  {
    id:'sanqi', name:'三七', alias:'田七、金不换', category:'zhixue',
    prop:'甘、微苦，温', meridian:'肝、胃',
    effect:'散瘀止血，消肿定痛',
    indication:'各种出血证、跌打瘀肿、胸腹刺痛',
    dosage:'3-10g，研粉吞服1-3g',
    origin:'云南、广西',
    bestOrigin:'云南文山（文三七，道地药材，品质最佳）',
    harvest:'种植3-7年后秋季采挖',
    processing:'洗净晒干，研粉或切片',
    contraindication:'孕妇忌用，血虚无瘀者不宜',
    wildFeature:'野生三七极为珍贵稀少（几近绝迹），个头小而质坚，体重皮皱，铜皮铁骨狮子头特征明显',
    plantedFeature:'种植品个头大，体重质坚。以"铜皮铁骨"（皮色铜绿、体重质坚）为佳',
    identifyTips:'正品有"铜皮铁骨狮子头"特征：表面灰棕色（铜皮），体重质坚击碎后断面灰绿色（铁骨），顶端有瘤状突起（狮子头）',
    appearance:'主根呈类圆锥形或圆柱形，表面灰褐色或灰黄色，有断续纵皱纹及支根痕',
    notes:'三七"止血不留瘀，化瘀不伤正"，为伤科要药'
  },
  {
    id:'aiye', name:'艾叶', alias:'艾草、灸草', category:'zhixue',
    prop:'辛、苦，温', meridian:'肝、脾、肾',
    effect:'温经止血，散寒止痛，调经安胎，除湿止痒',
    indication:'吐血衄血、月经过多、胎漏下血、少腹冷痛、宫寒不孕、皮肤瘙痒',
    dosage:'3-10g，外用适量',
    origin:'全国各地',
    bestOrigin:'湖北蕲春（蕲艾，道地药材）',
    harvest:'夏季花未开时采摘',
    processing:'晒干生用或制艾绒',
    contraindication:'阴虚血热者慎用',
    wildFeature:'野生蕲艾叶大而厚，毛多色白，艾绒产量高，香气浓郁',
    plantedFeature:'普通种植艾叶薄色淡，毛较少，出绒率低',
    identifyTips:'正品叶面灰绿色，叶背密被灰白色绒毛。蕲艾比普通艾叶宽大、毛密、香气浓',
    appearance:'多皱缩破碎，完整者呈卵状椭圆形，羽状深裂，上表面灰绿色，下面密被灰白色绒毛',
    notes:'艾灸为中医外治重要方法，蕲艾品质最优'
  },
  // ========== 化痰药 ==========
  {
    id:'banxia', name:'半夏', alias:'地文、三叶半夏', category:'huatan',
    prop:'辛，温，有毒', meridian:'脾、胃、肺',
    effect:'燥湿化痰，降逆止呕，消痞散结',
    indication:'湿痰寒痰、咳喘痰多、痰厥头痛、呕吐反胃、胸脘痞闷',
    dosage:'3-10g，一般炮制后使用',
    origin:'四川、湖北、河南、安徽',
    bestOrigin:'甘肃西和（道地药材）、四川',
    harvest:'夏秋二季茎叶茂盛时采挖',
    processing:'法半夏（甘草石灰制）、姜半夏（姜矾制）、清半夏（白矾制）',
    contraindication:'阴虚燥咳、出血者忌用。反乌头',
    wildFeature:'野生半夏块茎小而圆，表面白色光滑，粉性足，质坚实',
    plantedFeature:'种植品块茎较大，表面可能有水浸痕迹',
    identifyTips:'正品呈类球形，表面白色或浅黄色，上端有凹陷的芽痕（称脐眼）。味辛辣，生品刺喉',
    appearance:'类球形，有的稍偏斜，表面白色或浅黄白色，顶端中心有凹陷茎痕',
    notes:'生半夏有毒，必须炮制后使用。"反乌头"为十八反之一'
  },
  {
    id:'chuanbeimu', name:'川贝母', alias:'川贝、贝母', category:'huatan',
    prop:'苦、甘，微寒', meridian:'肺、心',
    effect:'清热润肺，化痰止咳，散结消痈',
    indication:'肺热燥咳、干咳少痰、阴虚劳嗽、瘰疬、肺痈、乳痈',
    dosage:'3-10g，研粉冲服1-2g',
    origin:'四川、西藏、云南、甘肃、青海',
    bestOrigin:'四川阿坝松潘（松贝，最佳）',
    harvest:'夏秋季或积雪融化后采挖',
    processing:'生用研粉',
    contraindication:'脾胃虚寒及寒痰湿痰者不宜。反乌头',
    wildFeature:'野生川贝（松贝）粒小浑圆，大瓣抱小瓣（怀中抱月），粉性足，价格昂贵',
    plantedFeature:'种植品（栽培川贝）个头稍大，但品相不如野生松贝',
    identifyTips:'松贝"怀中抱月"（两瓣大小悬殊，大瓣抱小瓣）为鉴别要点。以粒小、质坚、色白、粉性足者为佳',
    appearance:'类圆锥形或近球形，表面类白色，外有鳞瓣2枚，大小悬殊（大瓣紧抱小瓣），顶端闭合',
    notes:'川贝价贵，市场常有浙贝、平贝冒充，需注意鉴别'
  },
  // ========== 补虚药 ==========
  {
    id:'huangqi', name:'黄芪', alias:'北芪、绵芪', category:'buxu',
    prop:'甘，微温', meridian:'肺、脾',
    effect:'补气升阳，固表止汗，利水消肿，生津养血，托毒生肌',
    indication:'气虚乏力、食少便溏、中气下陷、久泻脱肛、自汗、水肿、痈疽不溃',
    dosage:'10-30g',
    origin:'内蒙古、山西、甘肃、黑龙江',
    bestOrigin:'内蒙古恒山（绵芪）、山西浑源（道地药材）',
    harvest:'春秋二季采挖',
    processing:'切片生用或蜜炙',
    contraindication:'表实邪盛、气滞湿阻者不宜',
    wildFeature:'野生黄芪根条长而匀，少分叉，外皮灰白色紧贴不易剥落，质绵韧，豆腥味浓',
    plantedFeature:'种植品根粗短而有分叉，外皮较松，质稍脆，豆腥味淡',
    identifyTips:'正品断面有明显放射性纹理（菊花心），嚼之有豆腥味且粘性。以条粗长、皱纹少、粉性足、味甜者为佳',
    appearance:'圆柱形，有的有分枝，表面淡棕黄色或淡棕褐色，有纵皱纹或纵沟',
    notes:'黄芪为"补气之长"，现代研究有增强免疫力作用'
  },
  {
    id:'renshen', name:'人参', alias:'高丽参、吉林参', category:'buxu',
    prop:'甘、微苦，微温', meridian:'脾、肺、心、肾',
    effect:'大补元气，复脉固脱，补脾益肺，生津养血，安神益智',
    indication:'体虚欲脱、肢冷脉微、脾虚食少、肺虚喘咳、津伤口渴、气血亏虚、久病虚羸、失眠健忘',
    dosage:'3-10g（另煎兑服），挽救虚脱15-30g',
    origin:'吉林、辽宁、黑龙江',
    bestOrigin:'吉林抚松（长白山人参，道地药材）',
    harvest:'秋季采挖（园参5-6年），野山参数十年',
    processing:'生晒参、红参（蒸制）、糖参',
    contraindication:'实证热证忌用，不宜与藜芦、五灵脂同用，不宜同时饮茶和食萝卜',
    wildFeature:'野山参须长条清、皮紧体灵、芦碗紧密排列、珍珠疙瘩明显，参体小而精，芦头长',
    plantedFeature:'园参根粗大，须多而短乱，芦碗稀疏，珍珠疙瘩少或无',
    identifyTips:'野山参"五形"鉴别：芦（长且碗密）、纹（肩部横纹深密）、体（短小精悍）、须（清疏如皮条）、珍珠点（须上瘤状突起）',
    appearance:'主根纺锤形或圆柱形，表面灰黄色，上部有横纹及细密浅纵纹，下部有支根及须根',
    notes:'人参为百草之王，但不宜滥用，实证忌服'
  },
  {
    id:'danggui', name:'当归', alias:'干归、秦归', category:'buxu',
    prop:'甘、辛，温', meridian:'肝、心、脾',
    effect:'补血活血，调经止痛，润肠通便',
    indication:'血虚萎黄、眩晕心悸、月经不调、经闭痛经、虚寒腹痛、跌打损伤、痈疽疮疡、肠燥便秘',
    dosage:'6-12g',
    origin:'甘肃、云南、四川、湖北',
    bestOrigin:'甘肃岷县（岷归/秦归，道地药材）',
    harvest:'秋末采挖',
    processing:'切片生用或酒炒',
    contraindication:'湿盛中满、大便泄泻者忌用',
    wildFeature:'野生当归极少，均为栽培',
    plantedFeature:'正品主根粗短，下部有多条支根，表面黄棕色至棕褐色，具纵皱纹',
    identifyTips:'正品有浓郁特异香气（归头/归身/归尾各有侧重）。断面黄白色有裂隙，有油点。以主根粗大、质柔油润、气香味甜者为佳',
    appearance:'根略呈圆柱形，根上端称"归头"，主体称"归身"，支根称"归尾"，表面黄棕色',
    notes:'归头止血，归身补血，归尾破血，全当归和血'
  },
  {
    id:'gouqizi', name:'枸杞子', alias:'枸杞、红耳坠', category:'buxu',
    prop:'甘，平', meridian:'肝、肾',
    effect:'滋补肝肾，益精明目',
    indication:'肝肾阴虚、腰膝酸软、头晕目眩、目昏多泪、虚劳精亏、消渴',
    dosage:'6-12g',
    origin:'宁夏、内蒙古、新疆、河北',
    bestOrigin:'宁夏中宁（道地药材，"中宁枸杞"最为著名）',
    harvest:'夏秋季果实呈红色时采收',
    processing:'晾晒至皮干硬',
    contraindication:'外感实热、脾虚泄泻者慎用',
    wildFeature:'野生枸杞粒小椭圆，皮薄肉少籽多，色暗红，味甘甜后微苦',
    plantedFeature:'种植品粒大饱满，色鲜红或暗红，肉厚籽少，味甜',
    identifyTips:'正品宁夏枸杞入水不沉底，有"白果底"（果蒂处白色标记）。以粒大肉厚、色红、少籽、味甜者为佳',
    appearance:'纺锤形或椭圆形，表面鲜红色或暗红色，表面有不规则皱纹，顶端有小突起柱头',
    notes:'枸杞为药食同源品，泡水、煮汤、泡酒均可'
  },
  {
    id:'shudi', name:'熟地黄', alias:'熟地、九地', category:'buxu',
    prop:'甘，微温', meridian:'肝、肾',
    effect:'补血滋阴，益精填髓',
    indication:'血虚萎黄、眩晕心悸、月经不调、肝肾阴虚、腰膝酸软、盗汗遗精、内热消渴',
    dosage:'10-30g',
    origin:'河南、山西、河北、山东',
    bestOrigin:'河南焦作（怀庆府地黄/怀地黄，道地药材，四大怀药之一）',
    harvest:'秋季采挖根部',
    processing:'酒拌蒸至内外色黑润（九蒸九晒）',
    contraindication:'脾虚食少、腹满便溏者不宜',
    wildFeature:'野生品少见，道地产区种植品品质优异',
    plantedFeature:'正品经九蒸九晒加工，质柔软粘腻，味甜如饴',
    identifyTips:'正品外面乌黑色有光泽，质柔软粘腻，断面滋润乌黑。味甜。以块大肉厚、质柔润者为佳',
    appearance:'不规则块片或长圆形，表面乌黑色有光泽，质柔软而带韧性，不易折断，断面乌黑色',
    notes:'生地清热凉血，熟地补血滋阴——炮制不同功效相反'
  },
  // ========== 收涩药 ==========
  {
    id:'shanzhuyu', name:'山茱萸', alias:'山萸肉、萸肉', category:'shouse',
    prop:'酸、涩，微温', meridian:'肝、肾',
    effect:'补益肝肾，收涩固脱',
    indication:'眩晕耳鸣、腰膝酸痛、阳痿遗精、遗尿尿频、大汗虚脱、内热消渴',
    dosage:'6-12g',
    origin:'浙江、河南、陕西、山西',
    bestOrigin:'浙江淳安（浙萸肉）、河南西峡（道地药材）',
    harvest:'秋末冬初果实变红时采收，去核用肉',
    processing:'去核取肉，生用或酒蒸',
    contraindication:'命门火炽、湿热下注者忌用',
    wildFeature:'野生山茱萸果小而肉薄，色暗紫红，酸味特浓',
    plantedFeature:'栽培品果大肉厚，色紫红至黑红，酸味适中',
    identifyTips:'正品为去核后的果肉，不规则片状或囊状，表面紫红色至紫黑色。味酸涩微苦',
    appearance:'果肉呈不规则片状或囊状，表面紫红色至紫黑色，皱缩，有光泽',
    notes:'六味地黄丸中山茱萸为臣药，补益肝肾'
  },
  {
    id:'wuweizi', name:'五味子', alias:'北五味、辽五味', category:'shouse',
    prop:'酸、甘，温', meridian:'肺、心、肾',
    effect:'收敛固涩，益气生津，补肾宁心',
    indication:'久咳虚喘、自汗盗汗、遗精滑精、久泻不止、津伤口渴、心悸失眠',
    dosage:'2-6g',
    origin:'辽宁、吉林、黑龙江、河北',
    bestOrigin:'辽宁（辽五味，道地药材）',
    harvest:'秋季果实成熟时采摘',
    processing:'晒干生用或蒸后晒干（制五味子）',
    contraindication:'外感表邪、内有实热者忌用',
    wildFeature:'野生北五味子果小粒密，肉厚色紫红油润，味酸甘带辛苦咸（五味俱全）',
    plantedFeature:'种植品果粒较大均匀，色红',
    identifyTips:'正品呈不规则球形，表面紫红色皱缩有光泽。以紫红色、粒大肉厚、油润者为佳。五味具备者药力强',
    appearance:'不规则球形，表面紫红色或暗红色，皱缩，有的有果柄痕，果肉柔软油润',
    notes:'五味子皮肉甘酸，核中辛苦，全果有咸味，故名"五味子"'
  },
];
